# Generated by Django 5.2.14 on 2026-05-22 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=5)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('theme', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Naipe',
                'verbose_name_plural': 'Naipes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('instruction', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Médio'), ('HARD', 'Difícil')], default='EASY', max_length=20)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('requires_evidence', models.BooleanField(default=True)),
                ('evidence_type', models.CharField(choices=[('NONE', 'Não exige evidência'), ('TEXT', 'Texto'), ('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo'), ('IMAGE_OR_VIDEO', 'Imagem ou vídeo')], default='IMAGE', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.suit')),
            ],
            options={
                'verbose_name': 'Carta',
                'verbose_name_plural': 'Cartas',
                'ordering': ('suit__name', 'value'),
                'constraints': [models.UniqueConstraint(fields=('suit', 'value'), name='unique_card_per_suit_and_value')],
            },
        ),
    ]
