# Generated by Django 5.2.14 on 2026-09-20 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_playergroup_mediators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('instruction', models.TextField()),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('points', models.PositiveSmallIntegerField(default=5)),
                ('evidence_type', models.CharField(choices=[('TEXT', 'Texto'), ('FILE', 'Arquivo'), ('ANY', 'Texto ou arquivo')], default='ANY', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('CANCELED', 'Cancelado')], db_index=True, default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flash_challenges', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(related_name='flash_challenges', to='groups.playergroup')),
            ],
            options={
                'ordering': ('-starts_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FlashChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='challenges/submissions/')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], db_index=True, default='PENDING', max_length=20)),
                ('points_awarded', models.PositiveSmallIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.flashchallenge')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flash_challenge_submissions', to='groups.playergroup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_challenge_submissions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flash_challenge_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='flashchallenge',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='challenges__status_e3b878_idx'),
        ),
        migrations.AddConstraint(
            model_name='flashchallengesubmission',
            constraint=models.UniqueConstraint(fields=('challenge', 'player', 'group'), name='unique_flash_submission_per_player_group'),
        ),
    ]
