from django.core.management.base import BaseCommand

from apps.cards.models import Card
from apps.cards.models import Suit


SUITS = [
    {
        "name": "Copas",
        "symbol": "♥",
        "color": "#D90429",
        "theme": "Atividade física",
        "description": "Cartas relacionadas a movimento, exercício físico e intensidade de treino.",
    },
    {
        "name": "Paus",
        "symbol": "♣",
        "color": "#222222",
        "theme": "Alimentação e hidratação",
        "description": "Cartas relacionadas a refeições saudáveis, hidratação e baixo valor calórico.",
    },
    {
        "name": "Ouros",
        "symbol": "♦",
        "color": "#D90429",
        "theme": "Gratidão e psicologia positiva",
        "description": "Cartas relacionadas a gratidão, respiração, mindfulness e experiências positivas.",
    },
    {
        "name": "Espadas",
        "symbol": "♠",
        "color": "#222222",
        "theme": "Comunidade e relações sociais",
        "description": "Cartas relacionadas a alegria compartilhada, contribuição e convite de novas pessoas.",
    },
]


CARDS = [
    {
        "suit": "Copas",
        "value": 1,
        "code": "COPAS_A",
        "title": "Atividade física leve por 15 minutos",
        "instruction": "Alguma atividade física por 15 min em intensidade baixa.",
        "category": "Atividade física",
        "difficulty": "EASY",
        "estimated_minutes": 15,
    },
    {
        "suit": "Copas",
        "value": 2,
        "code": "COPAS_02",
        "title": "Atividade física leve ou moderada",
        "instruction": "Alguma atividade física por 30 min em baixa intensidade OU por 15 min em média intensidade.",
        "category": "Atividade física",
        "difficulty": "EASY",
        "estimated_minutes": 30,
    },
    {
        "suit": "Copas",
        "value": 3,
        "code": "COPAS_03",
        "title": "Atividade física leve por 45 minutos",
        "instruction": "Alguma atividade física por 45 min em baixa intensidade.",
        "category": "Atividade física",
        "difficulty": "EASY",
        "estimated_minutes": 45,
    },
    {
        "suit": "Copas",
        "value": 4,
        "code": "COPAS_04",
        "title": "Atividade física moderada ou leve longa",
        "instruction": "Alguma atividade física por 30 min em média intensidade OU por 1h em baixa intensidade.",
        "category": "Atividade física",
        "difficulty": "MEDIUM",
        "estimated_minutes": 60,
    },
    {
        "suit": "Copas",
        "value": 5,
        "code": "COPAS_05",
        "title": "Atividade física média ou alta",
        "instruction": "Alguma atividade física por 45 min em média intensidade OU por 15 min em alta intensidade.",
        "category": "Atividade física",
        "difficulty": "MEDIUM",
        "estimated_minutes": 45,
    },
    {
        "suit": "Copas",
        "value": 6,
        "code": "COPAS_06",
        "title": "Atividade física média longa ou alta",
        "instruction": "Alguma atividade física por 1h em média intensidade OU por 30 min em alta intensidade.",
        "category": "Atividade física",
        "difficulty": "MEDIUM",
        "estimated_minutes": 60,
    },
    {
        "suit": "Copas",
        "value": 7,
        "code": "COPAS_07",
        "title": "Atividade física intensa por 45 minutos",
        "instruction": "Alguma atividade física por 45 min em alta intensidade.",
        "category": "Atividade física",
        "difficulty": "HARD",
        "estimated_minutes": 45,
    },
    {
        "suit": "Copas",
        "value": 8,
        "code": "COPAS_08",
        "title": "Atividade física intensa por 1 hora",
        "instruction": "Alguma atividade física por 1h em alta intensidade.",
        "category": "Atividade física",
        "difficulty": "HARD",
        "estimated_minutes": 60,
    },
    {
        "suit": "Copas",
        "value": 9,
        "code": "COPAS_09",
        "title": "Atividade física intensa acima de 1 hora",
        "instruction": "Alguma atividade física por mais de 1h e 10 min em alta intensidade.",
        "category": "Atividade física",
        "difficulty": "HARD",
        "estimated_minutes": 70,
    },

    {
        "suit": "Paus",
        "value": 1,
        "code": "PAUS_A",
        "title": "Água antes da primeira refeição",
        "instruction": "Beber de 350 ml a 500 ml de água antes da primeira refeição do dia.",
        "category": "Hidratação",
        "difficulty": "EASY",
        "estimated_minutes": 5,
    },
    {
        "suit": "Paus",
        "value": 2,
        "code": "PAUS_02",
        "title": "Uma refeição saudável",
        "instruction": "Realizar 1 refeição saudável.",
        "category": "Alimentação",
        "difficulty": "EASY",
        "estimated_minutes": 20,
    },
    {
        "suit": "Paus",
        "value": 3,
        "code": "PAUS_03",
        "title": "Duas refeições saudáveis",
        "instruction": "Realizar 2 refeições saudáveis OU 1 refeição saudável de baixo valor calórico.",
        "category": "Alimentação",
        "difficulty": "EASY",
        "estimated_minutes": 30,
    },
    {
        "suit": "Paus",
        "value": 4,
        "code": "PAUS_04",
        "title": "Três refeições saudáveis",
        "instruction": "Realizar 3 refeições saudáveis OU 2 refeições saudáveis de baixo valor calórico OU 1 refeição saudável de baixo valor calórico e com suplemento.",
        "category": "Alimentação",
        "difficulty": "MEDIUM",
        "estimated_minutes": 40,
    },
    {
        "suit": "Paus",
        "value": 5,
        "code": "PAUS_05",
        "title": "Quatro refeições saudáveis",
        "instruction": "Realizar 4 refeições saudáveis OU 2 refeições saudáveis e 1 refeição saudável de baixo valor calórico OU 1 refeição saudável de baixo valor calórico e com suplemento.",
        "category": "Alimentação",
        "difficulty": "MEDIUM",
        "estimated_minutes": 50,
    },
    {
        "suit": "Paus",
        "value": 6,
        "code": "PAUS_06",
        "title": "Refeições saudáveis com baixo valor calórico",
        "instruction": "Realizar 3 refeições saudáveis e 1 refeição saudável de baixo valor calórico OU 2 refeições saudáveis de baixo valor calórico e 1 refeição saudável OU 1 refeição saudável de baixo valor calórico e com suplemento e 1 refeição saudável.",
        "category": "Alimentação",
        "difficulty": "MEDIUM",
        "estimated_minutes": 50,
    },
    {
        "suit": "Paus",
        "value": 7,
        "code": "PAUS_07",
        "title": "Refeições saudáveis avançadas",
        "instruction": "Realizar 2 refeições saudáveis e 2 refeições saudáveis de baixo valor calórico OU 3 refeições saudáveis de baixo valor calórico OU 1 refeição saudável de baixo valor calórico e com suplemento e 1 refeição saudável de baixo valor calórico.",
        "category": "Alimentação",
        "difficulty": "MEDIUM",
        "estimated_minutes": 60,
    },
    {
        "suit": "Paus",
        "value": 8,
        "code": "PAUS_08",
        "title": "Refeições de baixo valor calórico",
        "instruction": "Realizar 3 refeições saudáveis de baixo valor calórico e 1 refeição saudável OU 1 refeição saudável de baixo valor calórico e com suplemento, 1 refeição saudável de baixo valor calórico e 1 refeição saudável.",
        "category": "Alimentação",
        "difficulty": "HARD",
        "estimated_minutes": 60,
    },
    {
        "suit": "Paus",
        "value": 9,
        "code": "PAUS_09",
        "title": "Quatro refeições de baixo valor calórico",
        "instruction": "Realizar 4 refeições saudáveis de baixo valor calórico OU 1 refeição saudável de baixo valor calórico e com suplemento e 2 refeições saudáveis de baixo valor calórico OU 2 refeições saudáveis de baixo valor calórico e com suplemento.",
        "category": "Alimentação",
        "difficulty": "HARD",
        "estimated_minutes": 60,
    },
    {
        "suit": "Paus",
        "value": 10,
        "code": "PAUS_10",
        "title": "Refeições de baixo valor calórico com suplemento",
        "instruction": "Realizar 3 refeições saudáveis de baixo valor calórico e 1 refeição saudável de baixo valor calórico com suplemento OU 2 refeições saudáveis de baixo valor calórico com suplemento e 2 refeições saudáveis OU 2 refeições saudáveis de baixo valor calórico com suplemento e 1 refeição de baixo valor calórico.",
        "category": "Alimentação",
        "difficulty": "HARD",
        "estimated_minutes": 60,
    },
    {
        "suit": "Paus",
        "value": 11,
        "code": "PAUS_J",
        "title": "Duas refeições de baixo valor calórico com suplemento",
        "instruction": "Realizar 2 refeições saudáveis de baixo valor calórico e 2 refeições saudáveis de baixo valor calórico com suplemento OU 3 refeições saudáveis de baixo valor calórico e com suplemento.",
        "category": "Alimentação",
        "difficulty": "HARD",
        "estimated_minutes": 60,
    },
    {
        "suit": "Paus",
        "value": 12,
        "code": "PAUS_Q",
        "title": "Refeição saudável com baixo valor calórico",
        "instruction": "Realizar 1 refeição saudável de baixo valor calórico e 3 refeições saudáveis de baixo valor calórico e com suplemento.",
        "category": "Alimentação",
        "difficulty": "HARD",
        "estimated_minutes": 60,
    },
    {
        "suit": "Paus",
        "value": 13,
        "code": "PAUS_K",
        "title": "Quatro refeições com suplemento",
        "instruction": "Realizar 4 refeições saudáveis de baixo valor calórico e com suplemento.",
        "category": "Alimentação",
        "difficulty": "HARD",
        "estimated_minutes": 60,
    },

    {
        "suit": "Ouros",
        "value": 1,
        "code": "OUROS_A",
        "title": "Agradecer por uma bênção",
        "instruction": "Agradecer por 1 bênção do dia de hoje e dizer o porquê.",
        "category": "Gratidão",
        "difficulty": "EASY",
        "estimated_minutes": 5,
    },
    {
        "suit": "Ouros",
        "value": 2,
        "code": "OUROS_02",
        "title": "Agradecer por duas bênçãos",
        "instruction": "Agradecer por 2 bênçãos do dia de hoje e dizer o porquê.",
        "category": "Gratidão",
        "difficulty": "EASY",
        "estimated_minutes": 5,
    },
    {
        "suit": "Ouros",
        "value": 3,
        "code": "OUROS_03",
        "title": "Agradecer por três bênçãos",
        "instruction": "Agradecer por 3 bênçãos do dia de hoje e dizer o porquê.",
        "category": "Gratidão",
        "difficulty": "EASY",
        "estimated_minutes": 8,
    },
    {
        "suit": "Ouros",
        "value": 4,
        "code": "OUROS_04",
        "title": "Agradecer por quatro bênçãos",
        "instruction": "Agradecer por 4 bênçãos do dia de hoje e dizer o porquê.",
        "category": "Gratidão",
        "difficulty": "EASY",
        "estimated_minutes": 10,
    },
    {
        "suit": "Ouros",
        "value": 5,
        "code": "OUROS_05",
        "title": "Mindfulness ou respiração 1 vez",
        "instruction": "Fazer mindfulness OU respiração 1x no dia.",
        "category": "Mindfulness",
        "difficulty": "EASY",
        "estimated_minutes": 10,
    },
    {
        "suit": "Ouros",
        "value": 6,
        "code": "OUROS_06",
        "title": "Mindfulness ou respiração 2 vezes",
        "instruction": "Fazer mindfulness OU respiração 2x no dia.",
        "category": "Mindfulness",
        "difficulty": "MEDIUM",
        "estimated_minutes": 20,
    },
    {
        "suit": "Ouros",
        "value": 7,
        "code": "OUROS_07",
        "title": "Mindfulness ou respiração 3 vezes",
        "instruction": "Fazer mindfulness OU respiração 3x no dia.",
        "category": "Mindfulness",
        "difficulty": "MEDIUM",
        "estimated_minutes": 30,
    },
    {
        "suit": "Ouros",
        "value": 8,
        "code": "OUROS_08",
        "title": "Atividade nova ou experiência positiva",
        "instruction": "Fazer 1 das atividades das cartas que você nunca fez OU viver 1 experiência positiva que não esteja nas cartas.",
        "category": "Psicologia positiva",
        "difficulty": "MEDIUM",
        "estimated_minutes": 20,
    },
    {
        "suit": "Ouros",
        "value": 9,
        "code": "OUROS_09",
        "title": "Duas atividades novas ou experiências positivas",
        "instruction": "Fazer 2 das atividades das cartas que você nunca fez OU viver 2 experiências positivas que não estejam nas cartas.",
        "category": "Psicologia positiva",
        "difficulty": "MEDIUM",
        "estimated_minutes": 30,
    },
    {
        "suit": "Ouros",
        "value": 10,
        "code": "OUROS_10",
        "title": "Três atividades novas ou experiências positivas",
        "instruction": "Fazer 3 das atividades das cartas que você nunca fez OU viver 3 experiências positivas que não estejam nas cartas.",
        "category": "Psicologia positiva",
        "difficulty": "HARD",
        "estimated_minutes": 40,
    },
    {
        "suit": "Ouros",
        "value": 11,
        "code": "OUROS_J",
        "title": "Inventário da psicologia positiva do Valete",
        "instruction": "Realizar 1 item do seu inventário da psicologia positiva do Valete.",
        "category": "Psicologia positiva",
        "difficulty": "HARD",
        "estimated_minutes": 30,
    },
    {
        "suit": "Ouros",
        "value": 12,
        "code": "OUROS_Q",
        "title": "Inventário da psicologia positiva da Dama",
        "instruction": "Realizar 1 item do seu inventário da psicologia positiva da Dama.",
        "category": "Psicologia positiva",
        "difficulty": "HARD",
        "estimated_minutes": 30,
    },
    {
        "suit": "Ouros",
        "value": 13,
        "code": "OUROS_K",
        "title": "Inventário da psicologia positiva do Rei",
        "instruction": "Realizar 1 item do seu inventário da psicologia positiva do Rei.",
        "category": "Psicologia positiva",
        "difficulty": "HARD",
        "estimated_minutes": 30,
    },

    {
        "suit": "Espadas",
        "value": 1,
        "code": "ESPADAS_A",
        "title": "Alegria compartilhada 1 vez",
        "instruction": "Demonstrar 1x alegria com a alegria do próximo OU reconhecer e parabenizar 1x alguém por uma conquista compartilhada.",
        "category": "Comunidade",
        "difficulty": "EASY",
        "estimated_minutes": 10,
    },
    {
        "suit": "Espadas",
        "value": 2,
        "code": "ESPADAS_02",
        "title": "Alegria compartilhada 2 vezes",
        "instruction": "Demonstrar 2x alegria com a alegria do próximo OU reconhecer e parabenizar 2x alguém por uma conquista compartilhada.",
        "category": "Comunidade",
        "difficulty": "EASY",
        "estimated_minutes": 15,
    },
    {
        "suit": "Espadas",
        "value": 3,
        "code": "ESPADAS_03",
        "title": "Compartilhar uma experiência saudável",
        "instruction": "Compartilhar 1 experiência saudável sua com a comunidade.",
        "category": "Comunidade",
        "difficulty": "EASY",
        "estimated_minutes": 10,
    },
    {
        "suit": "Espadas",
        "value": 4,
        "code": "ESPADAS_04",
        "title": "Compartilhar duas experiências saudáveis",
        "instruction": "Compartilhar 2 experiências saudáveis suas com a comunidade.",
        "category": "Comunidade",
        "difficulty": "MEDIUM",
        "estimated_minutes": 15,
    },
    {
        "suit": "Espadas",
        "value": 5,
        "code": "ESPADAS_05",
        "title": "Compartilhar três experiências saudáveis",
        "instruction": "Compartilhar 3 experiências saudáveis suas com a comunidade.",
        "category": "Comunidade",
        "difficulty": "MEDIUM",
        "estimated_minutes": 20,
    },
    {
        "suit": "Espadas",
        "value": 6,
        "code": "ESPADAS_06",
        "title": "Contribuir com um colega",
        "instruction": "Contribuir com 1 colega, puxando ele para cima.",
        "category": "Comunidade",
        "difficulty": "EASY",
        "estimated_minutes": 10,
    },
    {
        "suit": "Espadas",
        "value": 7,
        "code": "ESPADAS_07",
        "title": "Contribuir com dois colegas",
        "instruction": "Contribuir com 2 colegas, puxando ambos para cima.",
        "category": "Comunidade",
        "difficulty": "MEDIUM",
        "estimated_minutes": 15,
    },
    {
        "suit": "Espadas",
        "value": 8,
        "code": "ESPADAS_08",
        "title": "Convidar uma pessoa para jogar",
        "instruction": "Convidar 1 pessoa para jogar o PEDE.",
        "category": "Convite",
        "difficulty": "MEDIUM",
        "estimated_minutes": 10,
    },
    {
        "suit": "Espadas",
        "value": 9,
        "code": "ESPADAS_09",
        "title": "Convidar duas pessoas para jogar",
        "instruction": "Convidar 2 pessoas para jogar o PEDE.",
        "category": "Convite",
        "difficulty": "MEDIUM",
        "estimated_minutes": 15,
    },
    {
        "suit": "Espadas",
        "value": 10,
        "code": "ESPADAS_10",
        "title": "Convidar três pessoas para jogar",
        "instruction": "Convidar 3 pessoas para jogar o PEDE.",
        "category": "Convite",
        "difficulty": "HARD",
        "estimated_minutes": 20,
    },
    {
        "suit": "Espadas",
        "value": 11,
        "code": "ESPADAS_J",
        "title": "Convidar quatro pessoas para jogar",
        "instruction": "Convidar 4 pessoas para jogar o PEDE.",
        "category": "Convite",
        "difficulty": "HARD",
        "estimated_minutes": 25,
    },
    {
        "suit": "Espadas",
        "value": 12,
        "code": "ESPADAS_Q",
        "title": "Convidar cinco pessoas para jogar",
        "instruction": "Convidar 5 pessoas para jogar o PEDE.",
        "category": "Convite",
        "difficulty": "HARD",
        "estimated_minutes": 30,
    },
    {
        "suit": "Espadas",
        "value": 13,
        "code": "ESPADAS_K",
        "title": "Convidar seis pessoas para jogar",
        "instruction": "Convidar 6 pessoas para jogar o PEDE.",
        "category": "Convite",
        "difficulty": "HARD",
        "estimated_minutes": 35,
    },
]


class Command(BaseCommand):
    help = "Cria ou atualiza as cartas oficiais do jogo Última Cartada."

    def handle(self, *args, **options):
        suits_by_name = self._seed_suits()
        created_cards = 0
        updated_cards = 0

        for card_data in CARDS:
            suit = suits_by_name[card_data["suit"]]

            defaults = {
                "suit": suit,
                "value": card_data["value"],
                "title": card_data["title"],
                "description": card_data["instruction"],
                "instruction": card_data["instruction"],
                "category": card_data["category"],
                "difficulty": card_data["difficulty"],
                "estimated_minutes": card_data["estimated_minutes"],
                "requires_evidence": True,
                "evidence_type": "IMAGE",
                "is_active": True,
            }

            _, created = Card.objects.update_or_create(
                code=card_data["code"],
                defaults=defaults,
            )

            if created:
                created_cards += 1
            else:
                updated_cards += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Cartas processadas com sucesso. Criadas: {created_cards}. Atualizadas: {updated_cards}."
            )
        )

    def _seed_suits(self):
        suits_by_name = {}

        for suit_data in SUITS:
            suit, _ = Suit.objects.update_or_create(
                name=suit_data["name"],
                defaults={
                    "symbol": suit_data["symbol"],
                    "color": suit_data["color"],
                    "theme": suit_data["theme"],
                    "description": suit_data["description"],
                    "is_active": True,
                },
            )

            suits_by_name[suit.name] = suit

        return suits_by_name
