# Generated by Django 5.2.14 on 2026-09-20 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidences', '0002_initial'),
        ('games', '0002_game_evidence_deadline_time'),
        ('groups', '0002_playergroup_mediators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='community/posts/')),
                ('origin', models.CharField(choices=[('MANUAL', 'Publicação'), ('EVIDENCE', 'Evidência'), ('ACHIEVEMENT', 'Conquista')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Publicada'), ('HIDDEN', 'Oculta')], default='PUBLISHED', max_length=20)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_post', to='evidences.evidence')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='games.game')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='groups.playergroup')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicação da Comunidade',
                'verbose_name_plural': 'Publicações da Comunidade',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Publicada'), ('HIDDEN', 'Oculta')], default='PUBLISHED', max_length=20)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_community_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost')),
            ],
            options={
                'verbose_name': 'Comentário da Comunidade',
                'verbose_name_plural': 'Comentários da Comunidade',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CommunityReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('LIKE', 'Curtir'), ('SUPPORT', 'Apoiar'), ('CELEBRATE', 'Celebrar')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reação da Comunidade',
                'verbose_name_plural': 'Reações da Comunidade',
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['group', '-created_at'], name='community_c_group_i_55a041_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['game', '-created_at'], name='community_c_game_id_61ebf2_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['status', '-created_at'], name='community_c_status_012a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['post', 'created_at'], name='community_c_post_id_69cae9_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityreaction',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_reaction_per_post_and_user'),
        ),
    ]
