# Generated by Django 5.2.14 on 2026-05-22 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('groups', '0001_initial'),
        ('plays', '0001_initial'),
        ('rounds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ROUND_SCORED', 'Rodada pontuada'), ('EVIDENCE_APPROVED', 'Evidência aprovada'), ('MANUAL_ADJUSTMENT', 'Ajuste manual'), ('SCORE_RECALCULATED', 'Pontuação recalculada')], max_length=30)),
                ('previous_points', models.IntegerField(default=0)),
                ('new_points', models.IntegerField(default=0)),
                ('points_delta', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_score_logs', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='games.game')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='groups.playergroup')),
                ('play', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='plays.play')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='rounds.round')),
            ],
            options={
                'verbose_name': 'Log de Pontuação',
                'verbose_name_plural': 'Logs de Pontuação',
                'ordering': ('-created_at',),
            },
        ),
    ]
