# Generated by Django 5.2.14 on 2026-09-20 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_evidence_deadline_time'),
        ('groups', '0002_playergroup_mediators'),
        ('plays', '0002_play_evidence_due_at'),
        ('rounds', '0001_initial'),
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scorelog',
            name='source_reference',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='scorelog',
            name='action',
            field=models.CharField(choices=[('ROUND_SCORED', 'Rodada pontuada'), ('EVIDENCE_APPROVED', 'Evidência aprovada'), ('MANUAL_ADJUSTMENT', 'Ajuste manual'), ('SCORE_RECALCULATED', 'Pontuação recalculada'), ('FLASH_CHALLENGE_APPROVED', 'Desafio-relâmpago aprovado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scorelog',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='games.game'),
        ),
        migrations.AddConstraint(
            model_name='scorelog',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reference', ''), _negated=True), fields=('action', 'source_reference'), name='unique_score_action_source_reference'),
        ),
    ]
