# Generated by Django 5.2.14 on 2026-06-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEV', 'Desenvolvedor'), ('GENERAL_ADMIN', 'Administrador geral'), ('GAME_MEDIATOR', 'Mediador de jogos'), ('ADMIN', 'Administrador'), ('PLAYER', 'Jogador')], default='PLAYER', max_length=20),
        ),
    ]
