# Generated by Django 5.2.14 on 2026-09-20 00:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_game_evidence_deadline_time'),
        ('groups', '0002_playergroup_mediators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('interval_days', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Ativa'), ('FINISHED', 'Finalizada'), ('CANCELED', 'Cancelada')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ('-start_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='JourneyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('COMPLETED', 'Concluída'), ('CANCELED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journey_enrollments', to='groups.playergroup')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='journeys.journey')),
            ],
            options={
                'verbose_name': 'Matrícula em Jornada',
                'verbose_name_plural': 'Matrículas em Jornadas',
                'ordering': ('group__name',),
            },
        ),
        migrations.CreateModel(
            name='JourneyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('name', models.CharField(max_length=120)),
                ('duration_days', models.PositiveSmallIntegerField(default=21, editable=False)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='journeys.journey')),
            ],
            options={
                'verbose_name': 'Etapa da Jornada',
                'verbose_name_plural': 'Etapas da Jornada',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='JourneyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_games', to='journeys.journeyenrollment')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey_game', to='games.game')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journey_games', to='journeys.journeystage')),
            ],
            options={
                'verbose_name': 'Jogo da Jornada',
                'verbose_name_plural': 'Jogos da Jornada',
                'ordering': ('stage__order',),
            },
        ),
        migrations.AddConstraint(
            model_name='journeyenrollment',
            constraint=models.UniqueConstraint(fields=('journey', 'group'), name='unique_group_enrollment_per_journey'),
        ),
        migrations.AddConstraint(
            model_name='journeystage',
            constraint=models.UniqueConstraint(fields=('journey', 'order'), name='unique_stage_order_per_journey'),
        ),
        migrations.AddConstraint(
            model_name='journeygame',
            constraint=models.UniqueConstraint(fields=('enrollment', 'stage'), name='unique_game_per_enrollment_stage'),
        ),
    ]
