# Generated by Django 5.2.14 on 2026-09-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journeystage',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1), ('order__lte', 3)), name='journey_stage_order_between_1_and_3'),
        ),
        migrations.AddConstraint(
            model_name='journeystage',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days', 21)), name='journey_stage_duration_is_21_days'),
        ),
    ]
