# Generated by Django 5.2.14 on 2026-05-22 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Ativo'), ('FINISHED', 'Finalizado'), ('CANCELED', 'Cancelado')], default='DRAFT', max_length=20)),
                ('evidence_bonus_points', models.PositiveSmallIntegerField(default=3)),
                ('lowest_card_points', models.PositiveSmallIntegerField(default=1)),
                ('middle_card_points', models.PositiveSmallIntegerField(default=2)),
                ('highest_card_points', models.PositiveSmallIntegerField(default=3)),
                ('max_round_starts_per_player_per_day', models.PositiveSmallIntegerField(default=2)),
                ('allow_late_play', models.BooleanField(default=False)),
                ('show_ranking_to_players', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='groups.playergroup')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ('-start_date', 'name'),
            },
        ),
    ]
