# Generated by Django 5.2.14 on 2026-09-21 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TERMS', 'Termos de Uso'), ('PRIVACY', 'Política de Privacidade')], max_length=12)),
                ('version', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('requires_acceptance', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-published_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='legal_kind_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='legal.legaldocument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'document'), name='legal_acceptance_unique')],
            },
        ),
    ]
