# Generated by Django 5.2.14 on 2026-05-22 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horário de Rodada',
                'verbose_name_plural': 'Horários de Rodadas',
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('order',), name='unique_round_schedule_order')],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('OPEN', 'Aberta'), ('CLOSED', 'Fechada'), ('SCORED', 'Pontuada'), ('CANCELED', 'Cancelada')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.game')),
                ('selected_suit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='cards.suit')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_rounds', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='rounds.roundschedule')),
            ],
            options={
                'verbose_name': 'Rodada',
                'verbose_name_plural': 'Rodadas',
                'ordering': ('date', 'schedule__order'),
                'constraints': [models.UniqueConstraint(fields=('game', 'day_number', 'schedule'), name='unique_round_per_game_day_and_schedule')],
            },
        ),
    ]
