# Generated by Django 5.2.14 on 2026-06-14 02:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playergroup',
            name='mediators',
            field=models.ManyToManyField(blank=True, related_name='mediated_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
