# Generated by Django 5.2.14 on 2026-05-22 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('games', '0001_initial'),
        ('groups', '0001_initial'),
        ('rounds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('is_within_time', models.BooleanField(default=True)),
                ('is_round_starter', models.BooleanField(default=False)),
                ('base_points', models.PositiveSmallIntegerField(default=0)),
                ('bonus_points', models.PositiveSmallIntegerField(default=0)),
                ('total_points', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('VALID', 'Válida'), ('INVALID', 'Inválida'), ('REVIEWED', 'Revisada')], default='PENDING', max_length=20)),
                ('invalid_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plays', to='cards.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='games.game')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plays', to='groups.playergroup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='rounds.round')),
            ],
            options={
                'verbose_name': 'Jogada',
                'verbose_name_plural': 'Jogadas',
                'ordering': ('-played_at',),
                'constraints': [models.UniqueConstraint(fields=('round', 'player'), name='unique_play_per_round_and_player')],
            },
        ),
    ]
