# Generated by Django 5.2.14 on 2026-09-20 17:58

import apps.mentorship.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipcontent',
            name='document',
            field=models.FileField(blank=True, null=True, storage=apps.mentorship.storage.PrivateMentorshipStorage(), upload_to='mentorship/documents/'),
        ),
    ]
